import 'package:e_commerce_app/models/user_model/user_response.dart';

List<UserResponse> userData = [
  UserResponse(
    id: 1,
    fullName: "John Doe",
    userName: "john_doe",
    email: "johndoe@example.com",
    password: "password123",
    profileImage: "assets/profiles/profile_pic_1.png",
    locationName: 'New York', 
    headLineBio: "Food lover and chef",
    gender: "Male",
    membershipLevel: "Gold",
    onlineStatus: true,
    keepSignedIn: true,
    emailMarketing: true,
    totalOrders: 12,
  ),
  UserResponse(
    id: 2,
    fullName: "Jane Smith",
    userName: "jane_smith",
    email: "jane.smith@example.com",
    password: "mypassword",
    profileImage: "assets/profiles/profile_pic_2.png",
    locationName: 'New York', 
    headLineBio: "Healthy eating advocate",
    gender: "Female",
    membershipLevel: "Silver",
    onlineStatus: false,
    keepSignedIn: true,
    emailMarketing: false,
    totalOrders: 8,
  ),
  UserResponse(
    id: 3,
    fullName: "Alice Johnson",
    userName: "alice_j",
    email: "alice.johnson@example.com",
    password: "alice1234",
    profileImage: "assets/profiles/profile_pic_3.png",
    locationName: 'New York', 
    headLineBio: "Gourmet food enthusiast",
    gender: "Female",
    membershipLevel: "Bronze",
    onlineStatus: true,
    keepSignedIn: false,
    emailMarketing: true,
    totalOrders: 15,
  ),
  UserResponse(
    id: 4,
    fullName: "Bob Brown",
    userName: "bobbrown",
    email: "bob.brown@example.com",
    password: "bobby2020",
    profileImage: "assets/profiles/profile_pic_4.png",
    locationName: 'New York', 
    headLineBio: "Fast food fan",
    gender: "Male",
    membershipLevel: "Platinum",
    onlineStatus: false,
    keepSignedIn: true,
    emailMarketing: false,
    totalOrders: 20,
  ),
  UserResponse(
    id: 5,
    fullName: "Charlie Davis",
    userName: "charlie_d",
    email: "charlie.davis@example.com",
    password: "charlied",
    profileImage: "assets/profiles/profile_pic_5.png",
    locationName: 'New York', 
    headLineBio: "Vegetarian and cook",
    gender: "Male",
    membershipLevel: "Gold",
    onlineStatus: true,
    keepSignedIn: false,
    emailMarketing: true,
    totalOrders: 5,
  ),
  UserResponse(
    id: 6,
    fullName: "Deborah Harris",
    userName: "debbie_h",
    email: "deborah.harris@example.com",
    password: "debharris",
    profileImage: "assets/profiles/profile_pic_6.png",
    locationName: 'New York', 
    headLineBio: "Baking expert",
    gender: "Female",
    membershipLevel: "Silver",
    onlineStatus: false,
    keepSignedIn: true,
    emailMarketing: true,
    totalOrders: 10,
  ),
  UserResponse(
    id: 7,
    fullName: "Edward Clark",
    userName: "edward_c",
    email: "edward.clark@example.com",
    password: "edward123",
    profileImage: "assets/profiles/profile_pic_7.png",
    locationName: 'New York', 
    headLineBio: "Loves street food",
    gender: "Male",
    membershipLevel: "Bronze",
    onlineStatus: true,
    keepSignedIn: false,
    emailMarketing: false,
    totalOrders: 7,
  ),
  UserResponse(
    id: 8,
    fullName: "Fiona Martinez",
    userName: "fiona_m",
    email: "fiona.martinez@example.com",
    password: "fiona2021",
    profileImage: "assets/profiles/profile_pic_8.png",
    locationName: 'New York', 
    headLineBio: "Sushi expert",
    gender: "Female",
    membershipLevel: "Platinum",
    onlineStatus: false,
    keepSignedIn: true,
    emailMarketing: true,
    totalOrders: 14,
  ),
  UserResponse(
    id: 9,
    fullName: "George Wilson",
    userName: "george_w",
    email: "george.wilson@example.com",
    password: "georgew",
    profileImage: "assets/profiles/profile_pic_9.png",
    locationName: 'New York', 
    headLineBio: "BBQ master",
    gender: "Male",
    membershipLevel: "Gold",
    onlineStatus: true,
    keepSignedIn: true,
    emailMarketing: false,
    totalOrders: 6,
  ),
  UserResponse(
    id: 10,
    fullName: "Hannah Lee",
    userName: "hannah_lee",
    email: "hannah.lee@example.com",
    password: "hannah123",
    profileImage: "assets/profiles/profile_pic_10.png",
    locationName: 'New York', 
    headLineBio: "Dessert aficionado",
    gender: "Female",
    membershipLevel: "Silver",
    onlineStatus: false,
    keepSignedIn: false,
    emailMarketing: true,
    totalOrders: 9,
  ),
];