import 'package:e_commerce_app/models/user_model/user_data.dart';
import 'package:e_commerce_app/models/voucher_model/voucher_response.dart';

List<VoucherResponse> voucherData = [
  VoucherResponse(
    id: 1,
    user: userData[0],
    code: "VOUCHER10",
    discount: 10,
    description: "Get 10% off on your order",
    expiryDate: DateTime(2024, 12, 31),
  ),
  VoucherResponse(
    id: 2,
    user: userData[1],
    code: "DISCOUNT20",
    discount: 20,
    description: "Enjoy 20% discount on selected items",
    expiryDate: DateTime(2024, 11, 30),
  ),
  VoucherResponse(
    id: 3,
    user: userData[2],
    code: "SALE50",
    discount: 50,
    description: "Huge sale! Get 50% off on all items",
    expiryDate: DateTime(2025, 3, 15),
  ),
  VoucherResponse(
    id: 4,
    user: userData[3],
    code: "FREEDEL",
    discount: 100,
    description: "Free delivery on your next order",
    expiryDate: DateTime(2024, 10, 20),
  ),
  VoucherResponse(
    id: 5,
    user: userData[4],
    code: "BONUS25",
    discount: 25,
    description: "Get a bonus discount of 25% on your order",
    expiryDate: DateTime(2024, 9, 25),
  ),
  VoucherResponse(
    id: 6,
    user: userData[5],
    code: "FREESHIP",
    discount: 15,
    description: "Enjoy free shipping on your next purchase",
    expiryDate: DateTime(2024, 11, 10),
  ),
  VoucherResponse(
    id: 7,
    user: userData[6],
    code: "FALLSALE",
    discount: 30,
    description: "Fall sale! Get 30% off on all items",
    expiryDate: DateTime(2024, 10, 31),
  ),
  VoucherResponse(
    id: 8,
    user: userData[7],
    code: "WINTER50",
    discount: 50,
    description: "Winter special: 50% off on selected items",
    expiryDate: DateTime(2024, 12, 20),
  ),
  VoucherResponse(
    id: 9,
    user: userData[8],
    code: "SPRINGSALE",
    discount: 40,
    description: "Spring sale! Enjoy 40% off on all items",
    expiryDate: DateTime(2025, 4, 30),
  ),
  VoucherResponse(
    id: 10,
    user: userData[9],
    code: "SUMMERDEAL",
    discount: 35,
    description: "Summer deal: 35% off on selected items",
    expiryDate: DateTime(2025, 6, 15),
  ),
];
