import 'package:e_commerce_app/models/menu_model/menu_response.dart';
import 'package:e_commerce_app/models/restaurant_model/restaurant_data.dart';

List<MenuResponse> menuData = [
  MenuResponse(
    id: 1,
    restaurant: restaurantData[0],
    name: "Margherita Pizza",
    description: "Classic Margherita with fresh mozzarella and basil.",
    price: 12.99,
    foodType: "Main Course",
    imageUrl: "assets/menus/menu_pic_1.png",
    isAvailable: true,
  ),
  MenuResponse(
    id: 2,
    restaurant: restaurantData[1],
    name: "Pasta Carbonara",
    description: "Traditional Italian pasta with creamy sauce and pancetta.",
    price: 14.99,
    foodType: "Main Course",
    imageUrl: "assets/menus/menu_pic_2.png",
    isAvailable: true,
  ),
  MenuResponse(
    id: 3,
    restaurant: restaurantData[2],
    name: "Quinoa Salad",
    description: "Healthy quinoa salad with fresh vegetables and lemon dressing.",
    price: 10.99,
    foodType: "Appetizer",
    imageUrl: "assets/menus/menu_pic_3.png",
    isAvailable: true,
  ),
  MenuResponse(
    id: 4,
    restaurant: restaurantData[2],
    name: "Vegetarian Burger",
    description: "Delicious veggie burger with lettuce, tomato, and avocado.",
    price: 11.99,
    foodType: "Main Course",
    imageUrl: "assets/menus/menu_pic_4.png",
    isAvailable: false,
  ),
  MenuResponse(
    id: 5,
    restaurant: restaurantData[3],
    name: "Sushi Platter",
    description: "Assorted sushi platter with fresh sashimi and rolls.",
    price: 19.99,
    foodType: "Main Course",
    imageUrl: "assets/menus/menu_pic_5.png",
    isAvailable: true,
  ),
  MenuResponse(
    id: 6,
    restaurant: restaurantData[4],
    name: "Cheeseburger",
    description: "Juicy cheeseburger with cheddar cheese and special sauce.",
    price: 9.99,
    foodType: "Main Course",
    imageUrl: "assets/menus/menu_pic_6.png",
    isAvailable: true,
  ),
  MenuResponse(
    id: 7,
    restaurant: restaurantData[5],
    name: "Chicken Tikka Masala",
    description: "Spicy and creamy chicken tikka masala served with naan bread.",
    price: 13.99,
    foodType: "Main Course",
    imageUrl: "assets/menus/menu_pic_7.png",
    isAvailable: true,
  ),
  MenuResponse(
    id: 8,
    restaurant: restaurantData[6],
    name: "Tacos Al Pastor",
    description: "Traditional Mexican tacos with marinated pork and pineapple.",
    price: 7.99,
    foodType: "Main Course",
    imageUrl: "assets/menus/menu_pic_8.png",
    isAvailable: true,
  ),
  MenuResponse(
    id: 9,
    restaurant: restaurantData[7],
    name: "Croissant",
    description: "Flaky and buttery croissant, perfect for breakfast.",
    price: 3.99,
    foodType: "Desert",
    imageUrl: "assets/menus/menu_pic_9.png",
    isAvailable: true,
  ),
  MenuResponse(
    id: 10,
    restaurant: restaurantData[8],
    name: "Kung Pao Chicken",
    description: "Spicy Kung Pao chicken with peanuts and vegetables.",
    price: 12.49,
    foodType: "Main Course",
    imageUrl: "assets/menus/menu_pic_10.png",
    isAvailable: true,
  ),
];