import 'package:e_commerce_app/models/user_model/user_data.dart';
import 'package:e_commerce_app/models/testimonial_model/testimonial_response.dart';

List<TestimonialResponse> testimonialData = [
  TestimonialResponse(
    id: 1,
    user: userData[0],
    name: "John Doe",
    price: 25.0,
    comment: "Great food and excellent service!",
    date: "2024-05-20",
    numberOfRates: 10,
    starRating: 4.5,
    photoUrl: "assets/profiles/profile_pic_1.png",
  ),
  TestimonialResponse(
    id: 2,
    user: userData[1],
    name: "Alice Smith",
    price: 30.0,
    comment: "The ambiance was wonderful, and the food was delicious.",
    date: "2024-05-19",
    numberOfRates: 12,
    starRating: 5.0,
    photoUrl: "assets/profiles/profile_pic_2.png",
  ),
  TestimonialResponse(
    id: 3,
    user: userData[2],
    name: "Bob Johnson",
    price: 20.0,
    comment: "I loved the variety of dishes available. Will definitely visit again!",
    date: "2023-12-15",
    numberOfRates: 8,
    starRating: 4.0,
    photoUrl: "assets/profiles/profile_pic_3.png",
  ),
  TestimonialResponse(
    id: 4,
    user: userData[3],
    name: "Emily Davis",
    price: 35.0,
    comment: "The staff was very friendly and accommodating. Had a great time!",
    date: "2023-11-23",
    numberOfRates: 15,
    starRating: 4.5,
    photoUrl: "assets/profiles/profile_pic_4.png",
  ),
  TestimonialResponse(
    id: 5,
    user: userData[4],
    name: "David Wilson",
    price: 40.0,
    comment: "The food exceeded my expectations. Will recommend to friends!",
    date: "2023-10-31",
    numberOfRates: 20,
    starRating: 5.0,
    photoUrl: "assets/profiles/profile_pic_5.png",
  ),
  TestimonialResponse(
    id: 6,
    user: userData[5],
    name: "Emma Martinez",
    price: 28.0,
    comment: "Had a wonderful dining experience. The desserts were amazing!",
    date: "2023-09-18",
    numberOfRates: 10,
    starRating: 4.5,
    photoUrl: "assets/profiles/profile_pic_6.png",
  ),
  TestimonialResponse(
    id: 7,
    user: userData[6],
    name: "Michael Brown",
    price: 22.0,
    comment: "The restaurant had a cozy atmosphere. Enjoyed every moment!",
    date: "2023-08-27",
    numberOfRates: 7,
    starRating: 4.0,
    photoUrl: "assets/profiles/profile_pic_7.png",
  ),
  TestimonialResponse(
    id: 8,
    user: userData[7],
    name: "Sophia Clark",
    price: 27.0,
    comment: "Delicious food and prompt service. Will definitely come back again.",
    date: "2023-07-12",
    numberOfRates: 14,
    starRating: 4.5,
    photoUrl: "assets/profiles/profile_pic_8.png",
  ),
  TestimonialResponse(
    id: 9,
    user: userData[8],
    name: "Oliver Taylor",
    price: 18.0,
    comment: "Affordable prices and great quality food. Loved it!",
    date: "2023-06-25",
    numberOfRates: 6,
    starRating: 4.0,
    photoUrl: "assets/profiles/profile_pic_9.png",
  ),
  TestimonialResponse(
    id: 10,
    user: userData[9],
    name: "Ava Harris",
    price: 32.0,
    comment: "The staff went above and beyond to make our dining experience memorable.",
    date: "2023-05-11",
    numberOfRates: 9,
    starRating: 4.5,
    photoUrl: "assets/profiles/profile_pic_10.png",
  ),
];

