import 'package:e_commerce_app/models/restaurant_model/restaurant_response.dart';

List<RestaurantResponse> restaurantData = [
  RestaurantResponse(
    id: 1,
    name: "Gourmet Paradise",
    cuisineType: "Italian",
    location: "Food City",
    detailAddress: "123 Pasta Lane",
    phone: "123-456-7890",
    email: "contact@gourmetparadise.com",
    website: "www.gourmetparadise.com",
    rating: 4.5,
    profileImage: "assets/restaurants/restaurant_pic_1.png",
    coverImage: "assets/covers/cover_pic_1.png",
    bio: "A haven for Italian cuisine lovers",
    isOpen: true,
    hasDelivery: true,
  ),
  RestaurantResponse(
    id: 2,
    name: "Healthy Bites",
    cuisineType: "Vegetarian",
    location: "Veggie Town",
    detailAddress: "456 Green St",
    phone: "987-654-3210",
    email: "info@healthybites.com",
    website: "www.healthybites.com",
    rating: 4.7,
    profileImage: "assets/restaurants/restaurant_pic_2.png",
    coverImage: "assets/covers/cover_pic_2.png",
    bio: "Delicious vegetarian meals",
    isOpen: true,
    hasDelivery: false,
  ),
  RestaurantResponse(
    id: 3,
    name: "Sushi World",
    cuisineType: "Japanese",
    location: "Tokyo City",
    detailAddress: "789 Sushi Blvd",
    phone: "555-123-4567",
    email: "hello@sushiworld.com",
    website: "www.sushiworld.com",
    rating: 4.9,
    profileImage: "assets/restaurants/restaurant_pic_3.png",
    coverImage: "assets/covers/cover_pic_3.png",
    bio: "Authentic Japanese sushi",
    isOpen: false,
    hasDelivery: true,
  ),
  RestaurantResponse(
    id: 4,
    name: "Burger Hub",
    cuisineType: "American",
    location: "Fast Food City",
    detailAddress: "101 Burger Ave",
    phone: "111-222-3333",
    email: "contact@burgerhub.com",
    website: "www.burgerhub.com",
    rating: 4.2,
    profileImage: "assets/restaurants/restaurant_pic_4.png",
    coverImage: "assets/covers/cover_pic_4.png",
    bio: "Best burgers in town",
    isOpen: true,
    hasDelivery: true,
  ),
  RestaurantResponse(
    id: 5,
    name: "Curry Palace",
    cuisineType: "Indian",
    location: "Curry Town",
    detailAddress: "202 Spice Rd",
    phone: "222-333-4444",
    email: "support@currypalace.com",
    website: "www.currypalace.com",
    rating: 4.8,
    profileImage: "assets/restaurants/restaurant_pic_5.png",
    coverImage: "assets/covers/cover_pic_5.png",
    bio: "Exquisite Indian flavors",
    isOpen: true,
    hasDelivery: false,
  ),
  RestaurantResponse(
    id: 6,
    name: "Taco Fiesta",
    cuisineType: "Mexican",
    location: "Taco City",
    detailAddress: "303 Fiesta Lane",
    phone: "333-444-5555",
    email: "info@tacofiesta.com",
    website: "www.tacofiesta.com",
    rating: 4.6,
    profileImage: "assets/restaurants/restaurant_pic_6.png",
    coverImage: "assets/covers/cover_pic_6.png",
    bio: "Celebrating Mexican cuisine",
    isOpen: false,
    hasDelivery: true,
  ),
  RestaurantResponse(
    id: 7,
    name: "Bistro Delights",
    cuisineType: "French",
    location: "Paris City",
    detailAddress: "404 Bistro Blvd",
    phone: "444-555-6666",
    email: "reservations@bistrodelights.com",
    website: "www.bistrodelights.com",
    rating: 4.7,
    profileImage: "assets/restaurants/restaurant_pic_7.png",
    coverImage: "assets/covers/cover_pic_7.png",
    bio: "A taste of France",
    isOpen: true,
    hasDelivery: true,
  ),
  RestaurantResponse(
    id: 8,
    name: "Dragon's Breath",
    cuisineType: "Chinese",
    location: "China Town",
    detailAddress: "505 Dragon St",
    phone: "555-666-7777",
    email: "contact@dragonsbreath.com",
    website: "www.dragonsbreath.com",
    rating: 4.3,
    profileImage: "assets/restaurants/restaurant_pic_8.png",
    coverImage: "assets/covers/cover_pic_8.png",
    bio: "Authentic Chinese cuisine",
    isOpen: true,
    hasDelivery: false,
  ),
  RestaurantResponse(
    id: 9,
    name: "Mediterranean Magic",
    cuisineType: "Mediterranean",
    location: "Med Town",
    detailAddress: "606 Olive Rd",
    phone: "666-777-8888",
    email: "hello@medmagic.com",
    website: "www.medmagic.com",
    rating: 4.9,
    profileImage: "assets/restaurants/restaurant_pic_9.png",
    coverImage: "assets/covers/cover_pic_9.png",
    bio: "Mediterranean delights",
    isOpen: false,
    hasDelivery: true,
  ),
  RestaurantResponse(
    id: 10,
    name: "Dessert Haven",
    cuisineType: "Desserts",
    location: "Sweet City",
    detailAddress: "707 Sugar Lane",
    phone: "777-888-9999",
    email: "info@desserthaven.com",
    website: "www.desserthaven.com",
    rating: 4.8,
    profileImage: "assets/restaurants/restaurant_pic_10.png",
    coverImage: "assets/covers/cover_pic_10.png",
    bio: "Heavenly desserts",
    isOpen: true,
    hasDelivery: true,
  ),
];
