import 'package:e_commerce_app/models/message_model/message_response.dart';

List<MessageResponse> messageData = [
  MessageResponse(id: 1, text: "Hey there!", isMe: true, timeAgo: '9 minutes ago'),
  MessageResponse(id: 2, text: "Hi! How are you?", isMe: false, timeAgo: '10 minutes ago'),
  MessageResponse(id: 3, text: "I'm good, thanks! How about you?", isMe: true, timeAgo: '12 minutes ago'),
  MessageResponse(id: 4, text: "Long time, no see. You look great!", isMe: true, timeAgo: '12 minutes ago'),
  MessageResponse(id: 5, text: "I'm doing well too.", isMe: false, timeAgo: '14 minutes ago'),
  MessageResponse(id: 6, text: "You look great too.", isMe: false, timeAgo: '14 minutes ago'),
  MessageResponse(id: 7, text: "That's great to hear!", isMe: true, timeAgo: '16 minutes ago'),
  MessageResponse(id: 8, text: "Did you watch the game last night?", isMe: false, timeAgo: '18 minutes ago'),
  MessageResponse(id: 9, text: "Yes, it was amazing!", isMe: true, timeAgo: '20 minutes ago'),
  MessageResponse(id: 10, text: "I couldn't catch it. Who won?", isMe: false, timeAgo: '22 minutes ago'),
  MessageResponse(id: 11, text: "The home team won 3-2.", isMe: true, timeAgo: '24 minutes ago'),
  MessageResponse(id: 12, text: "Nice! They're on fire this season.", isMe: false, timeAgo: '26 minutes ago'),
  MessageResponse(id: 13, text: "Absolutely!", isMe: true, timeAgo: '28 minutes ago'),
  MessageResponse(id: 14, text: "By the way, are you free this weekend?", isMe: false, timeAgo: '30 minutes ago'),
  MessageResponse(id: 15, text: "Yes, I am. Why?", isMe: true, timeAgo: '32 minutes ago'),
  MessageResponse(id: 16, text: "Let's catch up for coffee.", isMe: false, timeAgo: '34 minutes ago'),
  MessageResponse(id: 17, text: "Sure, I'd love that!", isMe: true, timeAgo: '36 minutes ago'),
  MessageResponse(id: 18, text: "Great! How about Saturday afternoon?", isMe: false, timeAgo: '38 minutes ago'),
  MessageResponse(id: 19, text: "Sounds good to me. Shall we meet at Starbucks?", isMe: true, timeAgo: '40 minutes ago'),
  MessageResponse(id: 20, text: "Sure, Starbucks works for me. See you there!", isMe: false, timeAgo: '42 minutes ago'),
  MessageResponse(id: 21, text: "Perfect! Looking forward to it!", isMe: true, timeAgo: '44 minutes ago'),
  MessageResponse(id: 22, text: "Me too! Have a great day!", isMe: false, timeAgo: '46 minutes ago'),
  MessageResponse(id: 23, text: "You too!", isMe: true, timeAgo: '48 minutes ago'),
  MessageResponse(id: 24, text: "Hey, do you want to go for a hike this weekend?", isMe: false, timeAgo: '50 minutes ago'),
  MessageResponse(id: 25, text: "That sounds like a great idea!", isMe: true, timeAgo: '52 minutes ago'),
  MessageResponse(id: 26, text: "How about Sunday morning?", isMe: false, timeAgo: '54 minutes ago'),
  MessageResponse(id: 27, text: "Sure, Sunday morning works for me!", isMe: true, timeAgo: '56 minutes ago'),
  MessageResponse(id: 28, text: "Awesome! Let's meet at the trailhead at 9 am.", isMe: false, timeAgo: '58 minutes ago'),
  MessageResponse(id: 29, text: "Sounds like a plan!", isMe: true, timeAgo: '1 hour ago'),
  MessageResponse(id: 30, text: "Don't forget to bring some water and snacks!", isMe: false, timeAgo: '1 hour ago'),
  MessageResponse(id: 31, text: "Of course! Thanks for the reminder.", isMe: true, timeAgo: '1 hour ago'),
  MessageResponse(id: 32, text: "See you on Sunday!", isMe: false, timeAgo: '1 hour ago'),
];
